
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Speed Test
speedtestdotnet:
  scan_interval: 
    hours: 1
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload  

# Influx DB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: !secret home_assistant_db
  username: !secret home_assistant_db_user
  password: !secret home_assistant_db_pw
  max_retries: 3
  default_measurement: state

# Router
device_tracker:
  - platform: netgear
    host: !secret router_host
    username: !secret router_user
    password: !secret router_pw 
    new_device_defaults:
      track_new_devices: false    


